version: '3.8'

services:
  app:
    build: .
    container_name: cse-worktools-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/cseworktools"
    depends_on:
      - postgres
    networks:
      - cse-network

  postgres:
    image: postgres:14
    container_name: cse-worktools-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cseworktools
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cse-network

networks:
  cse-network:

volumes:
  postgres-data:
